### ISSUE TITLE
byte \x04 stops log output

### ISSUE THREAD

**Issue by SimonHeimberg** [php-censor/php-censor#116]
When there is \xa4 (byte with hex value A4) is in a log string, the log is stopped there (before saving to database).

Example to reproduce (nothing is printed after _Xa4):
```yaml
test:
    shell:
        - echo a
        - '/usr/bin/printf "b 123_X08\x08_X00\x00_Xa4\xa4_5432"'
        - echo c - is not shown
    shell_:
        - echo d - from next step is not shown
    phpunit: # no output shown
```

The full output is visible in `runtime/console.log`. But in the mysql database, the byte \xa4 and everything after is missing.

One of my tests generates some binary output by accident, and it contains this byte. I try to fix because this is not desired, but ...

(Should we handle other binary output special? Byte \x00 does not harm, but is not visible in the html page, the same may be valid for other bytes.
