### ISSUE TITLE
Additional project config (like .php-censor.yml but only in DB)

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#121]
I want to add additional project config (Like `.php-censor.yml` but only in DB). Which overlay some options from default project config (file) and has several exclusive options (Like: environments, secrets etc.). @SimonHeimberg Thank you for this idea (#87, #106).

It helps to unify special entities like environments (#41) and secrets (#14) and helps to add more features in the future with minimal changes.

Related issues: #106, #41, #14, #87, #109, #46.

Config example:
```yml
build_settings:
  clone_depth: 1
environments:
  pr:
  rc:
    - feature-A
  test:
    - feature-B
secrets:
  SECRET1: <SECRET1>
  SECRET2: <SECRET2>
```

@ss-gxp @SimonHeimberg @ketchoop What are you thing about it?
