### ISSUE TITLE
Status remains waiting

### ISSUE THREAD

**Issue by KuGelFaaaNg** [php-censor/php-censor#157]
## Expected behavior

*I actually expect a build to succeed or fail.*

## Actual behavior

The webhook is triggered. I trigger them from GitLab with a push in the master branch.
Even after two days, the status of all builds is still waiting.
The duration of each Build is 0 seconds.
I suspect the mistake in a faulty configuration, but do not know where to start. I can not find an error message anywhere.

## Steps to reproduce

*Trigger Webhook with git push.*

## Environment

* Ubuntu 16.04
* PHP 7.2

## .php-censor.yml

```yaml
build_settings:
    verbose: false
    prefer_symlink: false
    ignore:
        - "bootstrap"
        - "public"
        - "resources"
        - "storage"
        - "tests"
        - "vendor"
setup:
    composer:
        action: "install"
        prefer_dist: false
test:
    php_parallel_lint:
        ignore:
            - vendor/
            - _ide_helper.php
    php_code_sniffer:
        allowed_errors: 0
        allowed_warnings: -1
        path: "app"
        standard: "PSR1,PSR2,Zend"
    
    php_mess_detector:
        path: "app"
        ignore:
            - 'vendor'
        rules:
            - "cleancode"
            - "controversial"
            - "codesize"
            - "design"
            - "naming"
            - "unusedcode"
        allow_failures: false
        zero_config: true
    php_unit:
        config:
            - "phpunit.xml"
        path: "tests/"
    php_cpd:
        allow_failures: false
    php_docblock_checker:
        path: "app"
        allowed_warnings: 0
        skip_classes: false
        skip_methods: false
failure:
    email:
        committer: true
        default_mailto_address: name@domain.tld
complete:
    email:
        default_mailto_address: name@domain.tld
deploy:
    deployer:
        webhook_url: "http://gitlab.domain.tld/deploy/RandomKey"
        reason:      "PHP Censor Build #%BUILD% - %COMMIT_MESSAGE%"
        update_only: true
```

![php-censor](https://user-images.githubusercontent.com/14879811/36585593-cbb6cee2-187e-11e8-9479-2d0571c80abc.PNG)
