### ISSUE TITLE
Need Webhooks Notification like Travis

### ISSUE THREAD

**Issue by SamXiao** [php-censor/php-censor#184]
Should we add a webhooks notification like Travis?

**Comment by corpsee** [comment]
@SamXiao I am not clear what do you mean. Can you explan detailed?

**Comment by SamXiao** [comment]
@corpsee  Like this [Travis](https://docs.travis-ci.com/user/notifications/#Configuring-webhook-notifications)
Should we have a standard webhook notifier after build completed. So we can use it in our IM or somewhere quickly.

**Comment by corpsee** [comment]
@SamXiao Thanks for the explanation. I think it would be useful feature if somebody implement it. Pull requests are welcome :)

**Comment by ptejada** [comment]
A webhook plugin would work similar to how plugins like Slack work. In fact the Slack plugin functionality could be leveraged in this new `webhook` plugin. Do you guys have any specs for this implementation?

I was thinking something more along this lines for the config:
```
failure:
    webhook:
        url: http://hooks.chat.com/123
        type: json
        content: # Defines the payload of the request
            message: "Message with %placeholders%"
            customProp1: true
            customProp2: false
            ...
```
