### ISSUE TITLE
Build intermittently fails after 600 seconds with "Can`t build - status is not pending"

### ISSUE THREAD

**Issue by jwmwalrus** [php-censor/php-censor#205]
Hi.

When trying to run some functional tests, using headless chromium at port 9222 and Symfony's web server (with specific router) at port 8000, the test intermittently fails after 600 seconds with "Can`t build - status is not pending".

Moreover, the build log stops echoing output right after the headless chromium instance is started through supervisor.

Since the build fails intermittently, it also succeeds intermittently, for the same commit.

Am I missing something?

## project configuration

The configuration used for the builds follows.  Comments were added for each invocation of the project's setup script 
```yaml
build_settings:
    ignore:
        - "app"
        - "bin"
        - "node_modules"
        - "setup-data"
        - "var"
        - "vendor"
        - "web"

setup:
    composer:
        action: "show"
    shell:
        - "git submodule foreach git checkout %BRANCH%"
        - "cp /var/www/.ci-data/myproject/parameters.yml %BUILD_PATH%/app/config/parameters.yml"
        - "php %BUILD_PATH%/setup ci"    #composer install && npm ci
        - "php %BUILD_PATH%/setup testdb"   #setup test database (MySQL)
        - "php %BUILD_PATH%/setup runprod"   #run webpack build
        - "php %BUILD_PATH%/setup testports"   #make sure ports 9222 and 8000 are free
        - "supervisorctl start headless"
        - "php %BUILD_PATH%/bin/console server:start --router=web/test_router.php localhost:8000"

test:
    php_unit:
        config:
            - "phpunit.xml.dist"
        coverage: "tests/reports/coverage"
        args: "--testsuite MYTESTSUITE"

complete:
    shell:
        - "php %BUILD_PATH%/bin/console server:stop"
        - "supervisorctl stop headless"
    copy_build:
        directory: "/var/www/.ci-data/myproject/last-build"
        respect_ignore: false
        wipe: true
```

## Environment

* PHP Censor version: v0.22.0
* Operating System: Debian GNU/Linux 9.5 (stretch)
* PHP version: 7.2.7-1+0\~20180622080745.23+stretch~1.gbpfd8e2e
* MySQL/PostgreSQL version: 15.1 Distrib 10.1.26-MariaDB
