### ISSUE TITLE
Build never finishes when using codeception

### ISSUE THREAD

**Issue by jwmwalrus** [php-censor/php-censor#217]
Hi.

In order to get a much more accurate value of coverage (as I mentioned in #216), I'm trying to test running the equivalent acceptance suite using codeception.

Even though running the current tests should not take more than 20 minutes (and codeception's log at `/var/www/php-censor/runtime/builds/1/116_36f93be7/tests/_output/acceptance-2018-10-02` shows that all the tests already passed), PHP Censor's webview still keeps showing Codeception step as running ---and it never finishes doing so.

After php-censor.queue.lifetime's time value is reached (in my case, `6000`), then the log shows the infamous `Can`t build - status is not pending`. The only way to stop the build it is to delete it.

Codeception-related config is:

```yaml
test:
    codeception:
        config: "codeception.dist.yml"
        args: "acceptance tests/acceptance/ConfigBundle --coverage-html --html"
```

## Environment

* PHP Censor version: 0.23.0-23-gd6d11ad8
* Operating System: Debian GNU/Linux 9.5 (stretch)
* PHP version: 7.2.9-1+0\~20180910100512.5+stretch~1.gbpdaac35
* MySQL/PostgreSQL version: 15.1 Distrib 10.1.26-MariaDB
