### ISSUE TITLE
SlackNotify plugin kills worker process with error

### ISSUE THREAD

**Issue by benr77** [php-censor/php-censor#233]
## Expected behavior

The worker process does not die when the build with `slack_notify` completes

## Actual behavior

I see the following error when the build completes, as it tries to notify slack as per the slack notify plugin.

`Error: Class 'Maknz\Slack\Client' not found (uncaught exception) at /var/www/app/src/Plugin/SlackNotify.php line 86`

I'm using Docker, and this kills off the worker container completely, meaning it has to be restarted before any further builds can be processed. 

Slack notify config:
```
    slack_notify:
        webhook_url: 'https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxx
        room: '#phpcensor'
        username: 'PHPCensor'
        icon: ':ghost:'
        message: '%PROJECT_TITLE% - build %BUILD% completed'
        show_status: true
```

## Steps to reproduce

Just add that config to a build and the error should appear.

Presumably this is just a missing dependency in the composer.json

## Environment

* PHP Censor 0.24
* Docker
* 7.2
* MySQL
