### ISSUE TITLE
build with vendor/composer in a subdirectory

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#236]
for clarity i have moved my code source in /src, vendor is now in /src/vendor, while .php-censor.yml is in root.

How to help php-censor to find vendor/bin executable ?
the executable for codeception in my project is newer than the global phpcensor installed version.

## Expected behavior

calling the codecept executable present in ./src/vendor/bin/codecept and not in phpcensor directory

## Actual behavior
```shell
RUNNING PLUGIN: Codeception (Stage: Test)
Plugin options: {"config":".\/tests\/codeception.yml","allow_failures":false,"args":" -v "}
Looking for binary: codecept
Found in vendor/bin (global): codecept
Args: ["cd \"%s\" && \/data\/htdocs\/phpcensor\/vendor\/bin\/codecept run -c \"%s\"  -v  --xml","\/data\/htdocs\/phpcensor\/runtime\/builds\/7\/39023_9d17dd29\/","\/data\/htdocs\/phpcensor\/runtime\/builds\/7\/2523_9d17dd29\/.\/tests\/codeception.yml"]
Command: cd "./" && /data/htdocs/phpcensor/vendor/bin/codecept run -c "././tests/codeception.yml"  -v  --xml
Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPUnit_Framework_TestResult::addListener() must be an instance of PHPUnit_Framework_TestListener, instance of Codeception\PHPUnit\Listener given, called in /data/htdocs/phpcensor/vendor/codeception/codeception/src/Codeception/Codecept.php on line 108 and defined in /data/htdocs/phpcensor/vendor/phpunit/phpunit/src/Framework/TestResult.php:180
Stack trace:
#0 /data/htdocs/phpcensor/vendor/codeception/codeception/src/Codeception/Codecept.php(108): PHPUnit_Framework_TestResult->addListener(Object(Codeception\PHPUnit\Listener))
#1 /data/htdocs/phpcensor/vendor/codeception/codeception/src/Codeception/Codecept.php(87): Codeception\Codecept->registerPHPUnitListeners()
#2 /data/htdocs/phpcensor/vendor/codeception/codeception/src/Codeception/Command/Run.php(352): Codeception\Codecept->__construct(Array)
#3 /data/htdocs/phpcensor/vendor/symfony/console/Command/Command.php(255): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\C in /data/htdocs/phpcensor/vendor/phpunit/phpunit/src/Framework/TestResult.php on line 180

```
## Expected behavior
```shell
RUNNING PLUGIN: Codeception (Stage: Test)
Plugin options: {"config":".\/tests\/codeception.yml","allow_failures":false,"args":" -v "}
Looking for binary: codecept
Found in src/vendor/bin (local): codecept
Args: ["cd \"%s\" && \/data\/htdocs\/phpcensor\/runtime\/builds\/7\/39023_9d17dd29\/src\/vendor\/bin\/codecept run -c \"%s\"  -v  --xml","\/data\/htdocs\/phpcensor\/runtime\/builds\/7\/39023_9d17dd29\/","\/data\/htdocs\/phpcensor\/runtime\/builds\/7\/39023_9d17dd29\/.\/tests\/codeception.yml"]
Command: cd "./" && /data/htdocs/phpcensor/vendor/bin/codecept run -c "././tests/codeception.yml"  -v  --xml
Codeception PHP Testing Framework v2.5.1
Powered by PHPUnit 7.4.3 by Sebastian Bergmann and contributors.
Running with seed:


Functional Tests (348) -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Filesystem, Asserts, Yii2, REST, Db

```

## Steps to reproduce
I use the following structure for my application :
```shell
/tests/
/tests/codeception.yml
/test/unit...
/src/composer.json
/src/composer.lock
/.php-censor.yml
```

my php-censor config file :

using this php-censor.yml (some parts censured):
```yml
build_settings:
  verbose: true
  prefer_symlink: false
  allowed_warnings: 2
  ignore:
    - ./src/vendor
    - ./src/web/assets
  mysql:
    host: "127.0.0.1"
    user: "root"
    pass: "*****"
setup:
  mysql:
    - "DROP DATABASE IF EXISTS TEST_DB_BUILD_%BUILD%;"
    - "CREATE DATABASE TEST_DB_BUILD_%BUILD%  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
  composer:
    directory: "src"
    action: "install"
    prefer_dist: true
    
  shell:
    - "echo TEST_DB_BUILD_%BUILD%"
    - "sed -i -e 's,mysql:host=db;dbname=database_test,mysql:host=127.0.0.1;dbname=TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%src/config/db_mysql_test.php"
    - "sed -i -e 's,mysql:host=db;dbname=database_test,mysql:host=127.0.0.1;dbname=TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%src/config/db_oracle_test.php"
    - "sed -i -e 's,mysql:host=db;dbname=database_test,mysql:host=127.0.0.1;dbname=TEST_DB_BUILD_%BUILD%,g' %BUILD_PATH%tests/codeception.yml"
    # Bug identifié dans codeception, permet de passer les tests en attente de livraison de version > 2.5
    - "sed -i -e 's,codecept_debug(get_class,//odecept_debug(get_class,g' %BUILD_PATH%src/vendor/codeception/codeception/src/Codeception/Step.php"

    # Deploiement de l'application
    - "echo ajout droit execution"
    - "chmod +x %BUILD_PATH%tests/bin/yii"
    - "echo ajout Build de codeception"
    - "%BUILD_PATH%src/vendor/bin/codecept build -c %BUILD_PATH%tests/codeception.yml"
test:
  codeception:
    config: ./tests/codeception.yml
    allow_failures: false
    args: " -v "
  php_cpd:
    allow_failures: true
    ignore:
      - src/components/method/
      - src/agents/config/models
      - src/vendor
      - src/web/assets
      - src/runtime
      - src/controllers/configuration
      - tests/_support/_generated
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: php-censor@compagny.com

```
## Environment

* PHP Censor version 0.24
* Operating System 4.14.81-coreos 
* PHP version PHP 7.1.16 (cli) (built: Apr  5 2018 17:26:10) ( NTS )
* MySQL/PostgreSQL version non relative
