### ISSUE TITLE
Codeception test failed [The "./tests/acceptance/" directory does not exist.]

### ISSUE THREAD

**Issue by panosru** [php-censor/php-censor#244]
Codeception plugin fais for me, when I run it localy and with PhpStorm, it works fine:

```
Testing started at 01:06 ...
/Users/***/.bin/php /private/var/folders/3g/xng_tnzj6797frqqk20r69mw0000gn/T/ide-codeception.php run --report -o "reporters: report: PhpStorm_Codeception_ReportPrinter" --no-ansi --no-interaction -c /Users/****/PhpstormProjects/****/****/codeception.yml
Codeception PHP Testing Framework v2.5.1
Powered by PHPUnit 7.5.1 by Sebastian Bergmann and contributors.
Running with seed: 



Time: 1.94 seconds, Memory: 16.00MB

OK (57 tests, 75 assertions)

Process finished with exit code 0
```

This is my `codeception.yml` file:

```yml
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
extensions:
  enabled:
    - Codeception\Extension\RunFailed
coverage:
  enabled: true
  include:
    - src/*
    - tests/_support/MockApp/*
    - tests/_support/MockObjects/*
  exclude:
    - vendor/*
    - tests/*
  low_limit: 50
  high_limit: 90
```

And that is the ouput I'm getting from php censor (the rest of plugins worked fine):
```
RUNNING PLUGIN: Codeception (Stage: Test)
Codeception PHP Testing Framework v2.5.1
Powered by PHPUnit 7.5.1 by Sebastian Bergmann and contributors.
Running with seed: 

In Finder.php line 581:
                                                                               
  The "./tests/acceptance/" directory doe  
  s not exist.                                                                 
                                                                               

run [-o|--override OVERRIDE] [-e|--ext EXT] [--report] [--html [HTML]] [--xml [XML]] [--tap [TAP]] [--json [JSON]] [--colors] [--no-colors] [--silent] [--steps] [-d|--debug] [--coverage [COVERAGE]] [--coverage-html [COVERAGE-HTML]] [--coverage-xml [COVERAGE-XML]] [--coverage-text [COVERAGE-TEXT]] [--coverage-crap4j [COVERAGE-CRAP4J]] [--coverage-phpunit [COVERAGE-PHPUNIT]] [--no-exit] [-g|--group GROUP] [-s|--skip SKIP] [-x|--skip-group SKIP-GROUP] [--env ENV] [-f|--fail-fast] [--no-rebuild] [--seed SEED] [--] [<suite> [<test>]]


Exception: Warning: file_get_contents(./tests/_log/report.xml): failed to open stream: No such file or directory in /var/www/src/Helper/Xml.php line 62
PLUGIN: FAILED
```

Thanks!
