### ISSUE TITLE
[Bug] environnement variable from setup:env not avaible to setup:shell stage

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#261]
## Expected behavior

I set some var in the env: plugin and i want them to be avaible in the shell plugin and maybe later in codeception

## Actual behavior

```yaml
setup:
  env:
    - TEST_MYSQL_DATABASE: "TEST_DB_BUILD_%BUILD%"
    - TEST_MYSQL_HOST: 127.0.0.1
    - TEST_MYSQL_USER: root
  shell:
    - "set"
```

## Steps to reproduce

in the list of env, i don't get my defined environnement variables

## Environment

* PHP Censor version master
* Operating System 
* PHP version 7.1.16
* MySQL/PostgreSQL version

**Comment by corpsee** [comment]
@vinpel Thanks! Issue accepted.

**Comment by benr77** [comment]
I can confirm this. My CI build for a Symfony project has been based on using env vars defined in the setup section for a long time. I have e.g.
```
setup:
    env:
        APP_ENV: 'test'
        APP_DEBUG: '0'
    composer:
        action: 'install --no-suggest'
        prefer_dist: true
    shell:
        - bin/console fos:js-routing:dump --format=json
```
This makes the `bin/console` run as thought it were `APP_ENV=test bin/console` etc.

This has only been broken since sometime after the 1.0.2 release - it has definitely been working as expected right back from PHPCI days
