### ISSUE TITLE
[Question] Can I use last errors in plugins?

### ISSUE THREAD

**Issue by speker2010** [php-censor/php-censor#263]
It useful for legacy code. 
For exapmle:
```yaml
test:
  php_code_sniffer:
    allow_errors: last.errors_count
```
or
```yaml
test:
  php_code_sniffer:
    fail_on: has_new_errors
```
