### ISSUE TITLE
Add PHPUnit plugin options "allowed_[classes|methods|lines]_coverage"

### ISSUE THREAD

**Issue by corpsee** [php-censor/php-censor#299]
## Expected behavior

PHPunit plugin should fail when coverage is lower that `allowed_[classes|methods|lines]_coverage` option value. Config example:

```yml
test:
    php_unit:
        config:
            - "path/to/phpunit.xml"
        coverage: true
        allowed_lines_coverage: 60 
```

Also, according to #263 we should have ability to compare coverage with previous build. Config example:

```yml
test:
    php_unit:
        config:
            - "path/to/phpunit.xml"
        coverage: true
        allowed_methods_coverage: previous
        allowed_lines_coverage: previous - 0.1
```
