### ISSUE TITLE
[Bug] Unable To Get PHPSTAN Plugin To Run

### ISSUE THREAD

**Issue by mikebronner** [php-censor/php-censor#311]
## Expected behavior

PHPStan should run using the config shown in the setup.

## Actual behavior

1. PHPStan is not actually installed as a global PHP-CENSOR dependency, and thus requires to be installed with the project.
2. Even when configuring things according to the wiki, PHPSTAN still errors out. It appears to be missing an argument in the plugin code to point to the directories to be analyzed.

Output from verbose build:
```
RUNNING PLUGIN: phpstan (Stage: Test)
Directory: <BUILD_PATH>/app tests/
Plugin options: {"allow_failures":true,"binary_path":"vendor/bin","directory":"app tests"}
Looking for binary: phpstan, priority = local
Found in <BUILD_PATH>/vendor/bin (local): phpstan
Args: ["cd \"%s\" && <BUILD_PATH>/vendor/bin/phpstan analyze --error-format=json","<BUILD_PATH>/"]
Command: cd "<BUILD_PATH>/" && <BUILD_PATH>/vendor/bin/phpstan analyze --error-format=json
At least one path must be specified to analyse.
```

Project config:
```yml
build_settings:
    ignore:
        - vendor
        - tests

setup:
    composer:
        action: install

test:
    php_unit:
        config:
            - phpunit.xml.dist
        coverage: true

    php_code_sniffer:
        standard:       PSR2
        encoding:       UTF-8
        allow_failures: true
        ignore:
            - src/Migrations

    php_cpd:
        allow_failures: true

    php_loc:
        allow_failures: true

    php_parallel_lint:
        allow_failures: true

    security_checker:
        allow_failures: false

    phpstan:
        allow_failures: true
        binary_path: "vendor/bin"
```

Trying to install PHPSTAN in PHP-CENSOR's composer.json resulted in the following dependency conflicts:
```
Using version ^0.11.15 for phpstan/phpstan
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: nikic/php-parser[v4.2.3, v3.1.5].
    - Can only install one of: nikic/php-parser[v4.2.3, v3.1.5].
    - Can only install one of: nikic/php-parser[v4.2.3, v3.1.5].
    - phpstan/phpstan 0.11.15 requires nikic/php-parser ^4.2.3 -> satisfiable by nikic/php-parser[v4.2.3].
    - Installation request for phpstan/phpstan ^0.11.15 -> satisfiable by phpstan/phpstan[0.11.15].
    - Installation request for nikic/php-parser (locked at v3.1.5) -> satisfiable by nikic/php-parser[v3.1.5].


Installation failed, reverting ./composer.json to its original content.
```

## Steps to reproduce

n/a

## Environment

* PHP Censor version: 1.1.1
* Operating System: Ubuntu 18.04LTS
* PHP version: 7.2.21
* MySQL/PostgreSQL version: PG 11
