### ISSUE TITLE
[Bug] plugin "email" Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by vinpel** [php-censor/php-censor#339]
## Expected behavior
WIth a successfull build i get the current log :
```
RUNNING PLUGIN: Email (Stage: Complete)
Directory: <BUILD_PATH>/
Plugin options: {"default_mailto_address":"XXX@myvalideemail.fr"}
Committer email: 'XXX@myvalideemail.loc'
Committer option: 'false'
Addresses option: 'false'
Default mailTo option: 'XXX@myvalideemail.fr'
SMTP: 'false'
Exception: Address in mailbox given [] does not comply with RFC 2822, 3.6.2.
PLUGIN: FAILED (ALLOWED)
```
## Actual behavior

The status email is not send

## Steps to reproduce
the project have this php-censor.yml part : 
```yaml
complete:
  mysql:
    - "DROP DATABASE TEST_DB_BUILD_%BUILD%;"
  email:
    default_mailto_address: XXX@myvalideemail.fr
```
## Environment

* PHP Censor version **1.1.13**
* Operating System debian (docker)
* PHP version 7.2
* MySQL/PostgreSQL version

**Comment by corpsee** [comment]
@vinpel Thanks!

**Comment by vinpel** [comment]
i have fixed this with the folloging :
-> added the folowing package : ssmtp libpcre2-8-0
-> 2 parameters where empty (typo in env variable 
```yaml
  email_settings:
    from_address: ${PHPCENSOR_EMAIL_FROM}
    smtp_address: ${PHPCENSOR_EMAIL_SMTP}
```

The message is gone and email are correctly send.

The initial problem seem to be around php version without libPRCE installed  and swiftmailer who use an incompatible with certain version regular expression.
