### ISSUE TITLE
[Question] build_settings: Opposite of ignore?

### ISSUE THREAD

**Issue by kromonos** [php-censor/php-censor#370]
I'm playing around a bit with the build_settings and couldn't find in the documents, what I need.
In my current case, I would like to exclude a "/plugins" directory with `ignore`, but I would also like to include various plugins that come from me personally like "/plugins/my_own_plugin", so that they're getting catched by the tests although the parent folder has been excluded.
Is there a include part, or an option to negate? I.e.:

```yaml
build_settings:
    ignore:
        - vendor
        - tests
        - user/plugins
        - ! user/plugins/scrapper
```
