### ISSUE TITLE
[Bug] PostgreSQL plug-in fails

### ISSUE THREAD

**Issue by IndrekHaav** [php-censor/php-censor#402]
## Expected behavior

Queries specified in the build config being successfully executed.

## Actual behavior

Plug-in fails with the following error:

"The auto-commit mode cannot be changed for this driver"

## Environment

* PHP Censor version: 2.0.1
* Operating System: Ubuntu 20.04.2
* PHP version: 7.4.3
* PostgreSQL version: 11.10

**Comment by corpsee** [comment]
@IndrekHaav Could you also show your build config?

**Comment by IndrekHaav** [comment]
```
build_settings:
  clone_depth: "infinity"
  svn:
    username: "redacted"
    password: "redacted"
  pgsql:
    host: "127.0.0.1"
    port: "5432"
    user: "postgres"
    pass: ""

setup:
  shell:
    commands:
      - "cd %BUILD_PATH%/sql && psql -h 127.0.0.1 -f create_db.sql postgres postgres 1>/dev/null"

test:
  pgsql:
    queries:
      - "select generate_data('foobar');"

complete:
  pgsql:
    queries:
      - "drop database app;"
      - "drop user app;"
```

It's the test and complete stages that fail with the above error. Using the shell plug-in and passing the commands to `psql` (as in the setup stage) works fine.

I also set up PHP Censor on Debian, and the exact same build config works there. Versions are as follows:

 - PHP Censor version: 2.0.1
 - Operating System: Debian 10.7
 - PHP version: 7.4.14 (from https://deb.sury.org)
 - PostgreSQL version: 11.9
