### ISSUE TITLE
SVN - Username & password option

### ISSUE THREAD

**Issue by BrunoJunior** [php-censor/php-censor#70]
I've changed worker user and the new one didn't launch any svn command by ssh, so username and password wasn't saved.
When build ran, I had a connection error to SVN.
I tried to put username and password in global PHP Censor config (app/config.yml) :
```yml
php-censor:
  svn:
    username: <username>
    password: <password>
```
KO
I tried to change SVN URL : [username]:[password]@https://url/to/svn/repo
KO
I found a hack :
SVN URL : --username [username] --password [password] https://url/to/svn/repo
But it's not really user friendly
