### ISSUE TITLE
Possibility of excluding certain sniffs on PHPCS

### ISSUE THREAD

**Issue by DarkhejMaster** [php-censor/php-censor#88]
I think it should be added a option to exclude certain php codesniffer sniffs from to be tested.

**Comment by corpsee** [comment]
Thanks @DarkhejMaster. I will try to do something.

**Comment by SimonHeimberg** [comment]
As a workaround, you can create a phpcs.xml[.dist] in the project root.

not yet sure if you have to configure the follwing or if it is picked up automatically:
```yaml
test:
    php_code_sniffer:
        standard: "/phpcs.xml
```
